# training
conf_id: 040120_S2_CROP_spALL
algorithm: MemoryStage2
num_epochs: 30
hall_warm_up_epochs: 1
mem_warm_up_epochs: 5
limit_steps: 0
log_interval: 10

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: CCT_CIS_CROP_S2
class_indices: CCT_S2
train_split:  # Set to blank for full dataset
batch_size: 64
num_workers: 4
num_samples_cls: 4

# model
model_name: MemoryResNetClassifier
num_layers: 50
weights_init: ./weights/MemoryStage1/032720_S1_CROP_spALL_0.pth

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## memory
lr_memory: 0.01
momentum_memory: 0.9
weight_decay_memory: 0.0005
## lr_scheduler
step_size: 10
gamma: 0.1

# center loss weight
ctr_loss_weight: 0.01

# confidence
theta: 0.9

