# training
conf_id: 040120_S1_CROP_spALL
algorithm: PlainStage2
num_epochs: 30
log_interval: 10

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: CCT_CIS_CROP_S2
class_indices: CCT_S2
train_split:  # Set to blank for full dataset
batch_size: 64
num_workers: 4

# model
model_name: PlainResNetClassifier
num_layers: 50
weights_init: ./weights/PlainStage1/032620_S1_CROP_spALL_0.pth
conf_preds: ./weights/PlainStage1/032620_S1_CROP_spALL_0_conf_preds.npz


# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 10
gamma: 0.1

# confidence
theta: 0.9

