# training
conf_id: 041119
algorithm: PlainResNet
num_epochs: 60
log_interval: 1

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_S1
class_indices: MOZ_S1
batch_size: 128
num_workers: 8

# model
model_name: PlainResNetClassifier
num_layers: 18
weights_init: ImageNet

# optim
## feature
lr_feature: 0.01
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 20
gamma: 0.1
