# training
conf_id: 041220_S1
algorithm: MemoryStage1
num_epochs: 60
log_interval: 10
limit_steps: 1

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_S1
class_indices: MOZ_S1
train_transform: MOZ
train_split:  # Set to blank for full dataset
batch_size: 64
num_workers: 8
num_samples_cls: 4

# model
model_name: PlainResNetClassifier
num_layers: 50
weights_init: ImageNet

# optim
## feature
lr_feature: 0.01
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.1
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 15
gamma: 0.1

# confidence
theta: 0.9

