# training
conf_id: 041520_EP
algorithm: PlainResNet
num_epochs: 30
log_interval: 10
limit_steps: 0

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_EP
class_indices: MOZ_EP
train_transform: MOZ
train_split:  # Set to blank for full dataset
batch_size: 64
num_workers: 8

# model
model_name: PlainResNetClassifier
num_layers: 50
weights_init: ImageNet

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 10
gamma: 0.1

