# Session 0
# training
# Session 0
#conf_id: 072820_MOZ_S2_soft_iter_tune
#algorithm: GTPSMemoryStage2_ConfPseu_SoftIter_TUNE
#hall_warm_up_epochs:
#oltr_epochs: 30
#log_interval: 10
#no_up_freq: 10
#limit_steps: 1
#semi_iters: 3  # Iterations for semi-supervised learning
### lr_scheduler
#step_size: 10
#gamma: 0.1

# Session 1
conf_id: 072820_MOZ_S2_soft_iter_tune
algorithm: GTPSMemoryStage2_ConfPseu_SoftIter_TUNE
hall_warm_up_epochs:
oltr_epochs: 30
log_interval: 10
no_up_freq: 3
limit_steps: 1
semi_iters: 3  # Iterations for semi-supervised learning
## lr_scheduler
step_size: 10
gamma: 0.1

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_S2_GTPS_SoftIter
deploy_dataset_name: MOZ_S3_NEP
deploy_ood_dataset_name: MOZ_S2_LEFTOUT
class_indices: MOZ_S2
train_transform: MOZ
train_split:  # Set to blank for full dataset
batch_size: 96
num_workers: 8
num_samples_cls: 2

# model
model_name: MemoryResNetClassifier_SoftIter
num_layers: 50
weights_init: ./weights/GTPSMemoryStage2_ConfPseu/051620_MOZ_S2_0.pth

# optim
# Session 0, 79.646, no blur, no rotation
### feature
#lr_feature: 0.001
#momentum_feature: 0.9
#weight_decay_feature: 0.0005
### classifier
#lr_classifier: 0.01
#momentum_classifier: 0.9
#weight_decay_classifier: 0.0005
### memory
#lr_memory: 0.0001
#momentum_memory: 0.9
#weight_decay_memory: 0.0005
### lr_scheduler
#step_size: 10
#gamma: 0.1

# Session 1, blur rotation
## feature
lr_feature: 0.0001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
# lr_classifier: 0.01 # Session 0
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## memory
lr_memory: 0.0001
momentum_memory: 0.9
weight_decay_memory: 0.0005


# center loss weight
ctr_loss_weight: 0.01

# reachability
reachability_scale: 10.0 # Sess 0, 1
#reachability_scale: 7.0 # Sess 2
#reachability_scale_eval: 8.0
# reachability_scale_eval: 6.5
reachability_scale_eval: 7.0

# Soft labels
# Session 0, 79.646, no blur, no rotation
#T: 15  # Temperature
#alpha: 0.5  # Soft-hard ratio

# Session 1, blur rotation
T: 10  # Temperature
alpha: 0.5  # Soft-hard ratio

# confidence
theta: 0.95

