# training
conf_id: 051620_MOZ_S2
algorithm: GTPSMemoryStage2_ConfPseu
hall_warm_up_epochs: 20
oltr_epochs: 30
log_interval: 10
limit_steps: 1

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_S2_GTPS
deploy_dataset_name: MOZ_S3_NEP
class_indices: MOZ_S2
train_transform: MOZ
train_split:  # Set to blank for full dataset
batch_size: 96
num_workers: 8
num_samples_cls: 2

# model
model_name: MemoryResNetClassifier
num_layers: 50
weights_init: ./weights/MemoryStage1/041220_MOZ_S1_0.pth

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## memory
lr_memory: 0.0001
momentum_memory: 0.9
weight_decay_memory: 0.0005
## lr_scheduler
step_size: 10
gamma: 0.1

# center loss weight
ctr_loss_weight: 0.01

# reachability
reachability_scale: 10.0

# confidence
theta: 0.9

