# training
conf_id: 102320_MOZ_S2_SEMI
algorithm: PlainDistSemiStage2
num_epochs: 30
log_interval: 10
limit_steps: 0
semi_iters: 4  # Iterations for semi-supervised learning

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_S2_GTPS_SoftIter
deploy_dataset_name: MOZ_S3_NEP
deploy_ood_dataset_name: MOZ_S2_LEFTOUT
class_indices: MOZ_S2
train_transform: MOZ
train_split:  # Set to blank for full dataset
batch_size: 96
num_workers: 8

# model
model_name: PlainSemiResNetClassifier
num_layers: 50
weights_init: ./weights/MemoryStage1/041220_MOZ_S1_0.pth

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 10
gamma: 0.1

# confidence
theta: 0.95

# reachability
reachability_scale: 10.0 # Sess 0, 1
reachability_scale_eval: 7.0

# SoftIter
T: 10  # Temperature
alpha: 0.5  # Soft-hard ratio
