# training
conf_id: 042020_MOZ_S2
algorithm: PlainStage2
num_epochs: 40
log_interval: 10
limit_steps: 0

# data
dataset_root: /home/zhmiao/datasets/ecology
dataset_name: MOZ_S2
deploy_dataset_name: MOZ_S3_NEP
class_indices: MOZ_S2
train_transform: MOZ
train_split:  # Set to blank for full dataset
batch_size: 64
num_workers: 4

# model
model_name: PlainResNetClassifier
num_layers: 50
weights_init: ./weights/PlainStage1/041220_MOZ_S1_0.pth

# optim
## feature
lr_feature: 0.001
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 15
gamma: 0.1

# confidence
theta: 0.9

